@startuml
actor User
participant Endpoint[
    =usersController
    ----
    POST /api/v1/sendResetPasswordEmail/:userName
]
participant sendResetPasswordEmail[
    =usersHandler
    ----
    sendResetPasswordEmail()
]
participant getUserByUsername[
    =usersDataBaseAccess
    ----
    getUserByUsername()
]
participant addResetCodeToUser[
    =usersDataBaseAccess
    ----
    addResetCodeToUser()
]
database DynamoDB
participant usersUtils.sendResetPasswordEmail[
    =userUtils
    ----
    sendResetPasswordEmail()
]

User -> Endpoint: Request reset password email
Endpoint -> sendResetPasswordEmail: Forward request
sendResetPasswordEmail -> sendResetPasswordEmail: Verifies Schema

alt schema is invalid
sendResetPasswordEmail -> Endpoint: BadSchemaResponse
Endpoint -> User: 400: Bad Schema 
end

sendResetPasswordEmail -> getUserByUsername: Get User
getUserByUsername -> DynamoDB: Get User

alt DynamoDB error
DynamoDB -> getUserByUsername: Error
getUserByUsername -> sendResetPasswordEmail: Error
sendResetPasswordEmail -> Endpoint: AWSErrorResponse
Endpoint -> User: ErrorResponse
end

alt no such user
DynamoDB -> getUserByUsername: No Such User
getUserByUsername -> sendResetPasswordEmail: No Such User
sendResetPasswordEmail -> Endpoint: 401: No Such User
Endpoint -> User: 401: No User Found
end

DynamoDB -> getUserByUsername: returns user
getUserByUsername -> sendResetPasswordEmail: returns user
sendResetPasswordEmail -> sendResetPasswordEmail: generate reset code
sendResetPasswordEmail -> addResetCodeToUser: add reset code to user
addResetCodeToUser -> DynamoDB: add reset code to user

alt DynamoDB error
DynamoDB -> getUserByUsername: Error
getUserByUsername -> sendResetPasswordEmail: Error
sendResetPasswordEmail -> Endpoint: AWSErrorResponse
Endpoint -> User: ErrorResponse
end

DynamoDB -> addResetCodeToUser: reset code has been added to user
addResetCodeToUser -> sendResetPasswordEmail: reset code has been added to user
sendResetPasswordEmail -> usersUtils.sendResetPasswordEmail: send reset password email


alt error sending email
usersUtils.sendResetPasswordEmail -> sendResetPasswordEmail: Error
sendResetPasswordEmail -> Endpoint: Error
Endpoint -> User: Error
end

usersUtils.sendResetPasswordEmail -> sendResetPasswordEmail: Email has sent
sendResetPasswordEmail -> Endpoint: Email has sent
Endpoint -> User: Email has sent
@enduml