@startuml
actor User
participant Endpoint[
    =usersController
    ----
    POST /api/v1/updateUserPassword/
]
participant usersHandler.updateUserPassword[
    =usersHandler
    ----
    updateUserPassword()
]
participant getUserByUsername[
    =usersDataBaseAccess
    ----
    getUserByUsername()
]
participant usersDataBaseAccess.updateUserPassword[
    =usersDataBaseAccess
    ----
    updateUserPassword()
]
database DynamoDB
participant sanitizeUser[
    =userUtils
    ----
    sanitizeUser()
]

User -> Endpoint: reset password
Endpoint -> usersHandler.updateUserPassword: Forward request
usersHandler.updateUserPassword -> usersHandler.updateUserPassword: Verifies Schema

alt schema is invalid
usersHandler.updateUserPassword -> Endpoint: BadSchemaResponse
Endpoint -> User: 400: Bad Schema 
end

usersHandler.updateUserPassword -> getUserByUsername: Get User
getUserByUsername -> DynamoDB: Get User

alt DynamoDB error
DynamoDB -> getUserByUsername: Error
getUserByUsername -> usersHandler.updateUserPassword: Error
usersHandler.updateUserPassword -> Endpoint: AWSErrorResponse
Endpoint -> User: ErrorResponse
end

alt no such user
DynamoDB -> getUserByUsername: No Such User
getUserByUsername -> usersHandler.updateUserPassword: No Such User
usersHandler.updateUserPassword -> Endpoint: 401: No Such User
Endpoint -> User: 401: No User Found
end

DynamoDB -> getUserByUsername: returns user
getUserByUsername -> usersHandler.updateUserPassword: returns user
usersHandler.updateUserPassword ->usersHandler.updateUserPassword: does reset code match?

alt reset code does not match
usersHandler.updateUserPassword -> Endpoint: 401:Reset Code is Wrong
Endpoint -> User: 401:Reset Code is Wrong
end

usersHandler.updateUserPassword -> usersDataBaseAccess.updateUserPassword: update password
usersDataBaseAccess.updateUserPassword -> DynamoDB: update password

alt DynamoDB error
DynamoDB -> usersDataBaseAccess.updateUserPassword: Error
usersDataBaseAccess.updateUserPassword -> usersHandler.updateUserPassword: Error
usersHandler.updateUserPassword -> Endpoint: AWSErrorResponse
Endpoint -> User: ErrorResponse
end

DynamoDB -> usersDataBaseAccess.updateUserPassword: successfully updated user
usersDataBaseAccess.updateUserPassword -> usersHandler.updateUserPassword: successfully updated user

usersHandler.updateUserPassword -> sanitizeUser: sanitizeUser
sanitizeUser -> usersHandler.updateUserPassword: returns user without password or resetCode
usersHandler.updateUserPassword -> usersHandler.updateUserPassword: generate jwt for sanitized user
usersHandler.updateUserPassword -> Endpoint: return user and token
Endpoint -> User: return user and token
@enduml